name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: projectflow_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/projectflow_test
      REDIS_URL: redis://localhost:6379/0
      JWT_SECRET: test_secret

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Setup DB
        run: | 
          bundle exec rails db:prepare
      - name: Rubocop
        run: bundle exec rubocop
      - name: Brakeman
        run: bundle exec brakeman
      - name: RSpec
        run: bundle exec rspec